---
abstract: 'AnyEvent-based interface to the GNU Privacy Guard'
author:
  - 'Francis J. Lacoste <francis.lacoste@Contre.COM>'
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  Env::Path: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-GnuPG
requires:
  AnyEvent: '0'
  AnyEvent::Proc: '0.104'
  Async::Chain: '0'
  Carp: '0'
  Email::Address: '0'
  Exporter: '0'
  Try::Tiny: '0'
  constant: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/zurborg/libanyevent-gnupg-perl/issues
  homepage: https://github.com/zurborg/libanyevent-gnupg-perl
  repository: https://github.com/zurborg/libanyevent-gnupg-perl.git
version: '1.001'
x_contributors:
  - 'David Zurborg <port@david-zurb.org>'
  - 'Francis J. Lacoste <frajulac@contre.com>'
  - 'Mark Frost <mfrost@cpan.org>'
  - 'Robbie Bow <robbiebow@cpan.org>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
